import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html style={{ height: "100%" }} lang="en">
      <body style={{ padding: 0, margin: 0, height: "100%" }} className={inter.className}>
        {children}
      </body>
    </html>
  );
}
